name: list-apk
description: |
  list apk files
inputs:
  gc:
    required: true
    default: "false"
    description: apk gc flag
  arch:
    required: true
    default: x86_64
    description: architecture
runs:
  using: "composite"
  steps:
  - name: check if
    shell: bash
    run: |
      echo "filenum=$(docker compose exec -w /home/packager/packages/apk -T builder find . -type f -name \*.apk | wc -l | tr -d ' ')" >> $GITHUB_STATE
  - name: gc
    shell: bash
    if: inputs.gc == 'true' && env.STATE_filenum != 0
    run: |
      docker compose exec -T -w /build/mgmt builder python3 -m mgmt gc /home/packager/packages/apk/${{ inputs.arch }}/ --no-dry
  - name: index
    shell: bash
    if: env.STATE_filenum != 0
    run: |
      docker compose exec -T -w /home/packager/packages/apk builder dirindex make --template apache --recursive . --hide index.html
  - name: list apk
    shell: bash
    if: env.STATE_filenum != 0
    run: |
      echo "# package list" >> $GITHUB_STEP_SUMMARY
      echo "" >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
      docker compose exec -T -w /home/packager/packages/apk builder find . -type f -newer /build/.git >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
