name: list-apk
description: |
  list apk files
inputs:
  gc:
    required: true
    default: "false"
    description: apk gc flag
  arch:
    required: true
    default: x86_64
    description: architecture
runs:
  using: "composite"
  steps:
  - name: gc
    shell: bash
    if: inputs.gc == 'true'
    run: |
      if [ $(find /home/packager/packages/apk -type f -name \*.apk | wc -l) != 0 ] ; then
        docker compose exec -T -w /build/mgmt builder python3 -m mgmt gc /home/packager/packages/apk/${{ inputs.arch }}/ --no-dry
      fi
  - name: index
    shell: bash
    run: |
      if [ $(find /home/packager/packages/apk -type f -name \*.apk | wc -l) != 0 ] ; then
        docker compose exec -T -w /home/packager/packages/apk builder dirindex make --template apache --recursive . --hide index.html
      fi
  - name: list apk
    shell: bash
    run: |
      echo "# package list" >> $GITHUB_STEP_SUMMARY
      echo "" >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
      find /home/packager/packages/apk -type f -newer .git >> $GITHUB_STEP_SUMMARY
      echo '```' >> $GITHUB_STEP_SUMMARY
