name: rebuild all

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup abuild.conf
      shell: bash
      env:
        PACKAGER: ${{ secrets.PACKAGER }}
        KEY_NAME: ${{ secrets.KEY_NAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      run: |
        echo "PACKAGER=\"$PACKAGER\"" >> docker/builder/abuildconf/abuild.conf
        echo "PACKAGER_PRIVKEY=\"/home/packager/.abuild/$KEY_NAME.rsa\"" >> docker/builder/abuildconf/abuild.conf
        echo "$PRIVATE_KEY" > "docker/builder/abuildconf/$KEY_NAME.rsa"
        echo "$PUBLIC_KEY" > "docker/builder/abuildconf/$KEY_NAME.rsa.pub"
        chmod 600 "docker/builder/abuildconf/$KEY_NAME.rsa"
    - name: build image
      run: docker-compose build
    - name: boot builder
      run: docker-compose up -d builder
    - name: apk update
      run: docker-compose exec -T builder sudo apk update
    - name: build apk
      run: docker-compose exec -T builder sh /build/build-all.sh
    - name: get result
      run: |
        rm -rf output
        mkdir -p -m 0777 output
        env c_gid=$(id -g) c_uid=$(id -u) docker-compose up export
        ls -lR output
    - name: shutdown builder
      run: docker-compose down -v
    - name: build index
      shell: bash
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        KEY_NAME: ${{ secrets.KEY_NAME }}
      run: |
        pip install dirindex
        cd output
        find . -name index.html -delete
        rm -f .nojekyll
        echo "$PUBLIC_KEY" > "$KEY_NAME.rsa.pub"
        dirindex make --template apache --recursive .
        cd -
    - name: deploy to netlify
      run: npx netlify-cli deploy --dir=./output --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
