name: branch

on:
  push:
    branches-ignore: [gh-pages, main]
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        arch:
        - x86_64
        - aarch64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: boot
      uses: ./.github/actions/builder
      with:
        packager: ${{ secrets.PACKAGER }}
        key_name: ${{ secrets.KEY_NAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        arch: ${{ matrix.arch }}
    - name: build apk
      shell: bash
      run: |
        cd apk
        for i in $(git diff --name-only origin/main . | cut -f2 -d/ | sort -u) ; do
          [ -d "$i" ] || continue
          [ -f "${i}/APKBUILD" ] || continue
          grep -q "^${i}" ../mgmt/draft.list && continue
          [ -f ../mgmt/draft.list.${{ matrix.arch }} ] && grep -q "^${i}" ../mgmt/draft.list.${{ matrix.arch }} && continue
          docker compose exec -T builder sh /build/build-all.sh ${i} || exit 1
        done
    - name: list apk
      uses: ./.github/actions/list-apk
      with:
        arch: ${{ matrix.arch }}
    - name: shutdown builder
      uses: ./.github/actions/builder-fini
