name: branch

on:
  push:
    branches-ignore: [gh-pages, main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup abuild.conf
      run: |
        echo "PACKAGER=\"${{ secrets.PACKAGER }}\"" >> docker/builder/abuildconf/abuild.conf
        echo "PACKAGER_PRIVKEY=\"/home/packager/.abuild/${{ secrets.KEY_NAME }}.rsa\"" >> docker/builder/abuildconf/abuild.conf
        echo "${{ secrets.PRIVATE_KEY }}" > docker/builder/abuildconf/${{ secrets.KEY_NAME }}.rsa
        echo "${{ secrets.PUBLIC_KEY }}" > docker/builder/abuildconf/${{ secrets.KEY_NAME }}.rsa.pub
        chmod 600 docker/builder/abuildconf/${{ secrets.KEY_NAME }}.rsa
    - name: build image
      run: docker-compose build
    - name: boot builder
      run: docker-compose up -d builder
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-buildcache-${{ hashFiles('**/APKBUILD') }}
        restore-keys: ${{ runner.os }}-buildcache-
    - name: import cache
      run: docker-compose up cache-import
    - name: apk update
      run: docker-compose exec -T builder sudo apk update
    - name: build apk
      run: |
        cd apk
        for i in $(git diff --name-only origin/main . | cut -f2 -d/ | sort -u) ; do
          [ -d "$i" ] || continue
          [ -f "${i}/APKBUILD" ] || continue
          grep -q "^${i}" ../mgmt/draft.list && continue
          docker-compose exec -T builder sh /build/build-all.sh ${i} || exit 1
        done
    - name: list apk
      run: |
        mkdir -p -m 0777 output
        env c_gid=$(id -g) c_uid=$(id -u) docker-compose up export
        ls -lR output
    - name: export cache
      run: |
        mkdir -p -m 0777 cache
        docker-compose up cache-export
        ls -lR cache
    - name: shutdown builder
      run: docker-compose down -v
