name: branch

on:
  push:
    branches-ignore: [gh-pages, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup abuild.conf
      run: |
        echo "PACKAGER=\"${{ secrets.PACKAGER }}\"" >> builder.docker/abuildconf/abuild.conf
        echo "PACKAGER_PRIVKEY=\"/home/packager/.abuild/${{ secrets.KEY_NAME }}.rsa\"" >> builder.docker/abuildconf/abuild.conf
        echo "${{ secrets.PRIVATE_KEY }}" > builder.docker/abuildconf/${{ secrets.KEY_NAME }}.rsa
        echo "${{ secrets.PUBLIC_KEY }}" > builder.docker/abuildconf/${{ secrets.KEY_NAME }}.rsa.pub
        chmod 600 builder.docker/abuildconf/${{ secrets.KEY_NAME }}.rsa
    - name: build image
      run: docker-compose build
    - name: boot builder
      run: docker-compose up -d builder
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-buildcache-${{ hashFiles('**/APKBUILD') }}
        restore-keys: ${{ runner.os }}-buildcache-
    - name: import cache
      run: docker-compose up cache-import
    - name: build apk
      run: |
        for i in $(git diff --name-only origin/main) ; do
          [ -f "$i" ] || continue
          dn=$(dirname $i)
          [ -f "${dn}/APKBUILD" ] || continue
          grep -q "$dn" draft.list && continue
          docker-compose exec -T builder sh /build/build-all.sh ${dn}
        done
    - name: list apk
      run: |
        mkdir -p output
        docker-compose up export
        ls -lR output
    - name: export cache
      run: docker-compose up cache-export
    - name: shutdown builder
      run: docker-compose down -v
