name: check versions

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      run: |
        cd mgmt
        python -m venv .venv
        .venv/bin/pip install -r requirements.txt
    - name: check versions
      run: |
        cd mgmt
        .venv/bin/python -m mgmt check-version versions.yml
        .venv/bin/python -m mgmt check-repo --draftfile draft.list versions.yml https://dl-cdn.alpinelinux.org/alpine/edge/{main,community,testing}/x86_64/
