name: purge build cache

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-buildcache--${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildcache-
    - name: remove
      run: |
        rm -rf cache
        mkdir cache
