name: rebuild single package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package to build'
        required: true

jobs:
  build:
    strategy:
      matrix:
        arch:
        - x86_64
        - aarch64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup qemu
      uses: docker/setup-qemu-action@v2
    - name: setup abuild.conf
      shell: bash
      env:
        PACKAGER: ${{ secrets.PACKAGER }}
        KEY_NAME: ${{ secrets.KEY_NAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "PACKAGER=\"$PACKAGER\"" >> docker/builder/abuildconf/abuild.conf
        echo "PACKAGER_PRIVKEY=\"/home/packager/.abuild/$KEY_NAME.rsa\"" >> docker/builder/abuildconf/abuild.conf
        echo "$PRIVATE_KEY" > "docker/builder/abuildconf/$KEY_NAME.rsa"
        cp $KEY_NAME.rsa.pub docker/builder/abuildconf/
        cp $KEY_NAME.rsa.pub docker/test/
        chmod 600 "docker/builder/abuildconf/$KEY_NAME.rsa"
    - name: build image
      run: |
        docker compose -f docker compose.yml -f ${{ matrix.arch }}.yml build builder test
        docker pull alpine:edge
        docker compose -f docker compose.yml -f ${{ matrix.arch }}.yml build export
    - name: boot builder
      run: docker compose -f docker compose.yml -f ${{ matrix.arch }}.yml up -d builder
    - name: apk update
      run: docker compose exec -T builder sudo apk update
    - name: build apk
      run: docker compose exec -T builder sh /build/build-all.sh ${{ github.event.inputs.package }}
    - name: get result
      run: |
        rm -rf output
        mkdir -p -m 0777 output
        env c_gid=$(id -g) c_uid=$(id -u) docker compose up export
        ls -lR output
    - name: shutdown builder
      run: docker compose down -v
