name: rebuild single package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package to build'
        required: true

jobs:
  build:
    strategy:
      matrix:
        arch:
        - x86_64
        - aarch64
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: boot
      uses: ./.github/actions/builder
      with:
        packager: ${{ secrets.PACKAGER }}
        key_name: ${{ secrets.KEY_NAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        arch: ${{ matrix.arch }}
    - name: build apk
      run: docker compose exec -T builder sh /build/build-all.sh ${{ github.event.inputs.package }}
    - name: list apk
      uses: ./.github/actions/list-apk
      with:
        arch: ${{ matrix.arch }}
    - name: shutdown builder
      uses: ./.github/actions/builder-fini
