name: rebuild single package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package to build'
        required: true

jobs:
  build:
    strategy:
      matrix:
        arch:
        - runner: ubuntu-latest
          name: x86_64
        - runner: ubuntu-24.04-arm
          name: aarch64
    runs-on: ${{ matrix.arch.runner }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: boot
      uses: ./.github/actions/builder
      with:
        packager: ${{ secrets.PACKAGER }}
        key_name: ${{ secrets.KEY_NAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        arch: ${{ matrix.arch.name }}
    - name: build apk
      shell: bash
      run: docker compose exec -T builder sh /build/build-all.sh ${{ github.event.inputs.package }}
    - name: list apk
      uses: ./.github/actions/list-apk
      with:
        arch: ${{ matrix.arch.name }}
    - name: export apk
      shell: bash
      run: |
        mkdir output
        chmod 777 output
        docker compose up export
    - name: export artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-${{ matrix.arch.name }}
        path: output/${{ matrix.arch.name }}/*.apk
        if-no-files-found: error
    - name: shutdown builder
      uses: ./.github/actions/builder-fini
