name: auto update

on:
  workflow_dispatch: {}
  #schedule:
  #- cron: '0 20 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: boot
      uses: ./.github/actions/builder
      with:
        packager: ${{ secrets.PACKAGER }}
        key_name: ${{ secrets.KEY_NAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        arch: x86_64
    - name: chmod
      run: chmod -R go+wX apk .git
    - name: git config
      run: docker compose exec -T -w /build builder git config --global --add safe.directory /build
    - name: update version
      run: docker compose exec -T -w /build/mgmt builder python3 -m mgmt auto-update versions.yml
    - name: fix permission
      run: |
        sudo chown -R $(id -u):$(id -g) .git
    - name: git commit/push
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PUSH_TOKEN }}
        commit-message: auto update version
        title: auto update version
        add-paths: |
          apk
