name: auto update

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 20 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup abuild.conf
      shell: bash
      env:
        PACKAGER: ${{ secrets.PACKAGER }}
        KEY_NAME: ${{ secrets.KEY_NAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "PACKAGER=\"$PACKAGER\"" >> docker/builder/abuildconf/abuild.conf
        echo "PACKAGER_PRIVKEY=\"/home/packager/.abuild/$KEY_NAME.rsa\"" >> docker/builder/abuildconf/abuild.conf
        echo "$PRIVATE_KEY" > "docker/builder/abuildconf/$KEY_NAME.rsa"
        cp $KEY_NAME.rsa.pub docker/builder/abuildconf/$KEY_NAME.rsa.pub
        chmod 600 "docker/builder/abuildconf/$KEY_NAME.rsa"
    - name: build image
      run: docker compose build builder
    - name: boot builder
      run: docker compose up -d builder
    - name: chmod
      run: chmod -R go+wX apk .git
    - name: git config
      run: docker compose exec -T -w /build builder git config --global --add safe.directory /build
    - name: update version
      run: docker compose exec -T -w /build/mgmt builder python3 -m mgmt auto-update versions.yml
    - name: git commit/push
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PUSH_TOKEN }}
        commit-message: auto update version
        title: auto update version
        add-paths: |
          apk
